[package]
name = "open-headstage" # Changed to kebab-case
version = "0.1.0"
edition = "2021"
description = "An open-source binaural speaker simulation plugin for headphones."
license = "GPL-3.0-or-later" # SPDX identifier for GPLv3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "a33569bff6633a8b595b5c870d176e6e9cedcaad" }
backtrace = "=0.3.68" # Pinning to an exact older version

[lib]
crate-type = ["cdylib"]

[features]
default = ["nih_plug/vst3"]
vst3 = ["nih_plug/vst3"]
# lv2 = ["nih_plug/lv2"] # Temporarily removed until LV2 support in nih_plug is clarified
