[package]
name = "open-headstage"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git", optional = true }
egui-file-dialog = { version = "0.10.0", optional = true }
dirs = "5.0.1"

parking_lot = { version = "0.12", features = ["serde"] }

rustfft = "6.4.0"

[features]
default = ["ui"]
ui = ["nih_plug_egui", "egui-file-dialog"]

[build-dependencies]
bindgen = "0.70"

[lib]
crate-type = ["cdylib"]
