[package]
name = "open-headstage" # Changed to kebab-case
version = "0.1.0"
edition = "2021"
description = "An open-source binaural speaker simulation plugin for headphones."
license = "GPL-3.0-or-later" # SPDX identifier for GPLv3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nih-plug = { version = "0.5.1", features = ["serde"] }

[lib]
crate-type = ["cdylib"]

[features]
default = ["nih-plug/vst3", "nih-plug/lv2"]
vst3 = ["nih-plug/vst3"]
lv2 = ["nih-plug/lv2"]
