[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["vst3"] }
nih_plug_xtask = { git = "https://github.com/robbert-vdh/nih-plug.git" }
