name: Rust CI

on:
  push:
    branches: [ "main" ] # Or whatever your main branch is called
  pull_request:
    branches: [ "main" ] # Or whatever your main branch is called

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      GIT_TRACE: "1"
      GIT_CURL_VERBOSE: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl-dev libx11-xcb-dev libmysofa-dev libglib2.0-dev

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.87.0
          components: rustfmt, clippy # Add other components like 'llvm-tools-preview' if needed later

#      - name: Cache Cargo dependencies
#        uses: Swatinem/rust-cache@v2
#        with:
#          # Optional: specify a cache key prefix if you have multiple workflows
#          # prefix-key: "my-workflow-specific-prefix"
#          # Optional: share the cache between jobs (if you had multiple jobs in this workflow)
#          # shared-key: "shared-cache-key"
#          save-if: ${{ github.ref == 'refs/heads/main' }} # Only save cache on pushes to main

      - name: Clear Cargo cache
        run: |
          echo "Clearing Cargo registry cache..."
          rm -rf ~/.cargo/registry
          echo "Clearing Cargo git checkout cache..."
          rm -rf ~/.cargo/git
          echo "Cache clearing complete."

      - name: Update crate index
        run: cargo update --verbose

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy (Linter)
        run: cargo clippy --all-targets --all-features -- -D warnings # Fail on warnings

      - name: Build (debug)
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      # Optional: Build (release) - uncomment if you want to ensure release builds work too
      # - name: Build (release)
      #   run: cargo build --release --verbose
